local H=dofile('tests/prototype/orbs_support.lua');local M,A,O=H.M,H.A,H.O
local checks=0;local function check(v,msg)assert(v,msg);checks=checks+1 end
H.OrbPlan();local initial=M.Status()
check(initial.state=='IDLE' and H.Count('orb-spend')==0,'off by default')
SlashCmdList.NEXUS('orbs');check(NexusOrbPanel:IsShown() and H.Count('orb-spend')==0,'opening panel spends nothing')
check(M.SetRecycle(false),'fallback opt-in')
local preview,err=M.Prepare();check(not preview,'unapproved pool refused')
SlashCmdList.NEXUS('auto')
check(Nexus.RecomputeStats().autoEnabled==true,'control: ordinary master was enabled before approval')
H.Approve(2,false)
check(H.Count('orb-spend')==1,'one Orb requested after explicit confirmation')
local last=H.actions[#H.actions];check(last[1]=='orb-spend'and last[3]==1,'single Orb boundary')
check(Nexus.RecomputeStats().autoEnabled==false,'ordinary Auto off')
check(M.Status().reserved==1 and M.Status().spent==0,'exposure reserved not falsely billed confirmed')
check(not A.Take(410002) and not A.LockPerk(410007),'ordinary and permanent writes gated')
for i=1,5 do M.Pump()end;check(H.Count('orb-spend')==1,'no replay waiting for offer')
H.Offer();check(H.Count('take')==1,'select actual target offer')
check(M.Status().spent==1 and M.Status().reserved==0,'confirmed spend replaces exposure')
local before=H.Count('take');M.Pump();check(H.Count('take')==before,'no duplicate selection')
H.Result(410002,2)
check(M.Status().state=='COMPLETE','exact result completes target')
check(not M.BlocksOrdinary(),'ordinary owner released after settled completion')
check(Nexus.RecomputeStats().autoEnabled==false,'ordinary Auto never restarted')
check(Nexus.Store.State().orbRefinement.pending==nil,'recovery marker cleared only on result')
check(H.Count('orb-spend')==1,'target completion stops next spend')
print('PASS Orb real adapter/runtime/UI single-target loop checks='..checks)
