local H=dofile('tests/prototype/orbs_support.lua');local M=H.M
H.OrbPlan({{spellId=410002,quality=2,stacks=3}})
local f=Nexus.OrbPanel.Show();f.limit:SetText('3');f.start:Click()
assert(H.Count('orb-spend')==1 and M.Status().limit==3,'actual Start is the maximum/source approval')
local close
for _,b in ipairs(H.frames)do if b:GetParent()==f and b:GetText()=='Close'then close=b end end
assert(close);close:Click();assert(not f:IsShown() and M.Status().running)
Nexus.Panel.Show();H.Advance(.3)
local bar=assert(NexusPanel._orbControls)
assert(bar:IsVisible() and bar.primary:GetText()=='Pause','main controls are visible with detail closed')
H.Offer();H.Result(410002,2);H.Advance(.3)
assert(H.Count('orb-spend')==2,'closed detail continues confirmed attempts')
bar.primary:Click();assert(not M.Status().running,'main Pause works')
H.Offer();assert(H.Count('take')==1,'paused ready offer does not select')
bar.primary:Click();assert(H.Count('take')==2 and M.Status().limit==3,'main Resume retains approval')
bar.stop:Click();assert(not M.Status().running)
H.Result(410002,2);H.Advance(.5)
assert(M.Status().state=='STOPPED' and H.Count('orb-spend')==2,'main Stop permits passive settlement only')
assert(Nexus.RecomputeStats().autoEnabled==false,'ordinary rolling stays OFF')
print('PASS actual Start/Close and main-panel Pause/Resume/Stop with continuous confirmed attempts')
