local H=dofile('tests/prototype/orbs_support.lua');local M,A,O=H.M,H.A,H.O
local checks=0;local function check(v,m)assert(v,m);checks=checks+1 end
H.OrbPlan({{spellId=410002,quality=2,stacks=2}})
H.Approve(7,true,true)
check(M.Status().limit==1,'single-step always authorizes one Orb')
check(not M.Prepare(),'duplicate Start refuses')
check(not M.Confirm(H.lastApproval.token),'approval token is one-use')
check(M.Pause(),'pause accepted before offer')
H.Offer({{spellId=410001,quality=1},{spellId=410003,quality=0},{spellId=410008,quality=1}})
check(H.Count('take')==0 and M.Status().spent==1,'paused offer not selected; spend still reconciled')
check(M.Status().reserved==0,'spend reservation replaced not added')
check(M.Resume(),'explicit Resume accepts known waiting offer')
check(H.Count('take')==1,'one fallback selection after Resume')
H.Result(410001,1)
check(M.Status().state=='LIMIT' and H.Count('orb-spend')==1,'single-step stops at one with targets still missing')
check(not M.Resume(),'limit not bypassed by Resume')
SlashCmdList.NEXUS('auto');check(Nexus.RecomputeStats().autoEnabled==false,'master auto cannot restart while a limited run owns actions')
local a,err=M.PrepareLimitIncrease(3);check(a~=nil,err)
check(M.ConfirmLimit(a.token),'explicit limit confirmation')
check(M.Status().spent==1 and M.Status().limit==3 and not M.Status().running,'increase preserves usage, does not resume')
check(M.Resume(),'resume increased original limit')
check(H.Count('orb-spend')==2,'one next Orb, not duplicate first')
check(O.source==410001,'confirmed recyclable result prioritized')
check(M.Stop(),'Stop accepted with pending spend')
H.Offer();check(H.Count('take')==1,'Stop never auto-selects later offer')
-- Operator manually resolves the legitimate pending native offer.
H.service.SelectPerk(410002);H.Result(410002,2)
check(M.Status().state=='STOPPED' and not M.Status().pending,'passive result reconciled after Stop')
for i=1,5 do M.Pump()end
check(H.Count('orb-spend')==2 and not M.BlocksOrdinary(),'no auto-continuation after Stop')
check(not M.PrepareLimitIncrease(4),'stopped run cannot be resurrected by increasing its limit')
check(Nexus.RecomputeStats().autoEnabled==false,'ordinary Auto not restarted by terminal cleanup')
print('PASS Orb pause/resume/stop, single-step and explicit limit controls='..checks)
