local H=dofile('tests/prototype/orbs_support.lua');local M,O=H.M,H.O
dofile('tests/prototype/legacy_editbox_support.lua')(H)
H.OrbPlan();O.charges=0
local count=#H.actions
local ok,f=pcall(Nexus.OrbPanel.Show)
assert(ok,'legacy idle Orb render failed: '..tostring(f))
assert(f.limit.Enable==nil and f.limit.Disable==nil and f.limit.IsEnabled==nil,'fixture must not supply Button methods')
assert(f.limit.UnknownCapitalizedMethod==nil,'fixture must not invent unknown methods')
assert(f.limit.mouseEnabled and f.limit.keyboardEnabled,'idle maximum must be editable')
assert(f.limit:GetText()=='10' and f.usage:GetText()=='Orbs used: 0 / 10','actual maximum and usage must render')
assert(f.status:GetText():find('No confirmed Orbs are available.',1,true),'zero balance explanation must render')
assert(not f.start:IsEnabled() and not f.stop:IsEnabled(),'zero balance cannot start a run')
assert(not f.advanced:IsShown() and f:GetHeight()==445,'Advanced starts hidden in the closed-size panel')
f.limit:SetFocus();assert(H.TypeLimit(f,'3'))
Nexus.OrbPanel.Refresh()
assert(f.limit:HasFocus() and f.limit:GetText()=='3','passive refresh must preserve idle typing')
f.limit:GetScript('OnEnterPressed')(f.limit)
assert(not f.limit:HasFocus() and M.Status().config.maxOrbs==3,'Enter saves the idle maximum and releases focus')
f.limit:SetFocus();assert(H.TypeLimit(f,'9'));f.limit:GetScript('OnEscapePressed')(f.limit)
assert(not f.limit:HasFocus() and f.limit:GetText()=='3','Escape restores the saved maximum')
H.OrbButton('Advanced',f):Click();assert(f.advanced:IsShown() and f:GetHeight()==660)
H.OrbButton('Advanced',f):Click();assert(not f.advanced:IsShown() and f:GetHeight()==445)
f.limit:SetFocus();H.OrbButton('Close',f):Click()
assert(not f:IsShown() and not f.limit:HasFocus(),'Close releases the hidden input focus')
assert(#H.actions==count,'opening/editing/closing the zero-balance panel submits no gameplay action')
print('PASS strict legacy EditBox idle/zero balance/max usage/status/focus/Advanced/Close')
