-- Lost watchdog provenance and strict late-grant admission, through the real adapter.
local R=dofile('tests/prototype/select_recovery_support.lua')
local scenario,finish=R.Checks()
scenario('watchdog retains the unresolved Select',function(check)
 local H,A=R.Boot();H.Offer();assert(A.Take(R.X))
 H.Advance(12)
 check(A.InFlight()==true,'watchdog must retain own Select intent')
 check(#A.PendingActions()>0,'watchdog must retain pending provenance')
 check((A.Owned().bySpell[R.X] or 0)==0,'intent never counts as ownership')
 check(H.perks.pendingSelectSpellId==R.X,'no native latch write')
 H.perks.pendingSelectSpellId=nil;H.Offer(R.next);H.Advance(.2)
 check(A.InFlight()==true,'late latch clear without grant remains unresolved')
 R.Grant(H,R.X);H.Advance(.2)
 check(A.InFlight()==false,'exact late grant plus clear latch settles own Select')
 check(A.Take(R.Y)==true,'fresh next-board Select is admitted after proof')
 check(H.Count(R.X)==1 and H.Count(R.Y)==1,'no replay of the old choice')
end)
scenario('matching grant with a dead latch cannot admit an action',function(check)
 local H,A=R.Boot();H.Offer();assert(A.Take(R.X));H.Advance(12)
 R.Grant(H,R.X);H.Offer(R.next)
 check(A.InFlight()==true,'grant seen while native latch remains set stays held')
 local before=H.selectAttempts;A.Take(R.Y)
 check(H.selectAttempts==before,'held latch must block before native Select call')
 H.perks.pendingSelectSpellId=nil;A.Poll();H.Advance(.2)
 check(A.InFlight()==false,'cleared latch with matching grant permits settlement')
end)
scenario('same board and cleared latch do not prove refusal',function(check)
 local H,A=R.Boot();H.Offer();assert(A.Take(R.X))
 H.perks.pendingSelectSpellId=nil;A.Poll();H.Advance(.2)
 check(A.InFlight()==true,'same-board latch clearance is not authoritative refusal')
 check((A.Owned().bySpell[R.X] or 0)==0,'same-board clearance cannot create ownership')
 R.Grant(H,R.X);H.Advance(.2)
 check(A.InFlight()==false,'matching grant settles even if board stayed the same')
end)
for _,wait in ipairs({0,12})do
 scenario('hooked manual same-spell overlap at '..wait..' seconds',function(check)
  local H,A=R.Boot();H.Offer();assert(A.Take(R.X));H.Advance(wait)
  H.service.SelectPerk(R.X) -- Native return is not exposed by the post-hook.
  R.Grant(H,R.X);H.perks.pendingSelectSpellId=nil;H.Offer(R.next);H.Advance(.2)
  check(A.InFlight()==true,'one count rise cannot settle ambiguous same-spell requests')
  check(H.Count(R.X)==1,'fake service refused external duplicate; no fabricated grant')
 end)
end
scenario('old copy/new table/unrelated grant are not a new exact grant',function(check)
 local H,A=R.Boot(true);H.Offer();assert(A.Take(R.X))
 H.perks.pendingSelectSpellId=nil;H.Offer(R.next)
 H.granted=H.Clone(H.granted);R.Grant(H,R.Z);H.Advance(12)
 check(A.InFlight()==true,'old copy and unrelated grant preserve uncertainty')
 check(A.Owned().bySpell[R.X]==1,'only the old confirmed copy is owned')
end)
finish()
