-- Actual old runtime behavior, without requiring any newly introduced API.
local R=dofile('tests/prototype/select_recovery_support.lua')
local scenario,finish=R.Checks()
scenario('paced continuing rechecks and no duplicate during no response',function(check)
 local H,A=R.Boot();R.AutoSubmit(H);R.Travel(H)
 local first=H.grantedRequests;H.Advance(12)
 check(H.grantedRequests>first,'settled Auto ON must request read-only granted rechecks')
 local early=H.grantedRequests;H.Advance(300)
 check(H.grantedRequests>early,'slow rechecks continue after the early burst')
 check(H.grantedRequests-early<=32,'slow refreshes are paced, not a request storm')
 check(H.Auto() and H.selectAttempts==1,'no response retains Auto selection without Select resend')
 check((A.Owned().bySpell[R.X] or 0)==0,'rechecks do not invent ownership')
end)
for _,beforeLeave in ipairs({0,12})do
 scenario('late exact grant safely resumes; wait before leave '..beforeLeave,function(check)
  local H,A=R.Boot();R.AutoSubmit(H);H.Advance(beforeLeave);R.Travel(H)
  H.Advance(12);R.Grant(H,R.X);H.Offer(R.next);H.Advance(2)
  check(H.Count()==1,'matching grant with native Select flag still set holds actions')
  check(H.perks.pendingSelectSpellId==R.X,'no native latch is cleared by recovery')
  H.perks.pendingSelectSpellId=nil;A.Poll();H.Notify();H.Advance(8)
  check(H.Auto(),'recovery keeps Auto selected')
  check(H.Count(R.Y)==1,'late attributable grant and latch clearance resume a fresh decision')
  check(H.Count(R.X)==1,'safe recovery never replays already granted X')
 end)
end
scenario('loading and Auto OFF pause read rechecks',function(check)
 local H,A=R.Boot();R.AutoSubmit(H);H.Fire('PLAYER_LEAVING_WORLD')
 local before=H.grantedRequests;H.Advance(20)
 check(H.grantedRequests==before,'no recovery refresh while loading')
 H.Fire('PLAYER_ENTERING_WORLD');H.Advance(4)
 SlashCmdList.NEXUS('auto');assert(not H.Auto(),'fixture Auto OFF')
 before=H.grantedRequests;H.Advance(35)
 check(H.grantedRequests==before and H.Count()==1,'Auto OFF sends neither refresh nor action')
end)
scenario('unrelated grant and changed board remain unconfirmed',function(check)
 local H,A=R.Boot();R.AutoSubmit(H);R.Travel(H)
 R.Grant(H,R.Z);H.perks.pendingSelectSpellId=nil;H.Offer(R.next);H.Advance(20)
 check(H.Count()==1 and H.Auto(),'unrelated grant cannot release the world hold')
 check((A.Owned().bySpell[R.X] or 0)==0,'changed board cannot create ownership')
end)
scenario('Auto off/on does not discard unresolved own Select',function(check)
 local H,A=R.Boot();R.AutoSubmit(H);R.Travel(H);H.Advance(12)
 H.perks.pendingSelectSpellId=nil;H.Offer(R.initial);H.Advance(.2)
 SlashCmdList.NEXUS('auto');assert(not H.Auto(),'fixture OFF')
 SlashCmdList.NEXUS('auto');H.Advance(8)
 check(H.Auto() and H.selectAttempts==1,'re-enable restarts rechecks without blind Select replay')
 check((A.Owned().bySpell[R.X] or 0)==0,'re-enable is not grant evidence')
end)
finish()
